[module]
  [module.hugoVersion]
    extended=true
    min = "0.68.3"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false # Not allow HTML in md files
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  [params.theme_config]
    date_format = "02-01-2006"
